#!/bin/bash
# Syntax: mkrinex zipdir out [teqcoptions]
# Description: Leica MDB/RINEX GNSS hourly zipped data file convertion to daily RINEX
# Arguments:
#	zipdir		Directory of *.zip Leica data files (*.m??.zip or *.m?? or *.??o.zip)
#	out		Either output directory to write rinex (must exist), or any output rinex filename
#	teqcoptions	Any options to add (example: -O.dec 30 -O.rt "receiver" -O.at "antenna")
#
# Author: F. Beauducel / DOMERAPI <beauducel@ipgp.fr>
# Created: 2014-01-12
# Updated: 2016-03-10


tmpdir=$(mktemp -d /tmp/mkrinex.XXXXXXXXXX)

zipdir=$1
#zipfiles=$(ls $1/*.zip $1/*.m??)
zipfiles=$(find $1 -name "*.zip" -o -name "*.m??" | sort)
#echo "** zipfiles = $zipfiles"

outdir=$2

if [ "$#" -ge 3 ]
then
	shift
	shift
	teqcopt=$@
fi

# unzips all mdb files (-o option is mandatory to avoid prompting in some circumstances !)
for f in $zipfiles
do
	if [[ $f == *".zip" ]]; then
		unzip -oq $f -d $tmpdir
	else
		cp -a $f $tmpdir/
	fi

done

wildcard="*.m??"
#rawfiles=$(ls $tmpdir/$wildcard)
rawfiles=$(find $tmpdir -name "$wildcard" | sort )
navfiles="$rawfiles"
teqcfmt="-lei mdb"
# no mdb files... try rinex!
if [ -z "$rawfiles" ]; then
	wildcard="*.??o"
	rawfiles=$(ls $tmpdir/$wildcard)
	navfiles=$(ls $tmpdir/*.??n)
	teqcfmt=""
fi

# gets the station code from the filename
for f in $rawfiles
do
	#echo $f
	mdbfile=$(basename $f)
	code=${mdbfile:0:4}
	rinex=$outdir/${mdbfile:0:8}
done
code=$(echo $code | tr '[:lower:]' '[:upper:]')

# gets additionnal information from the node


tmprnx=$tmpdir/rinex
tmpnav=$tmpdir/nav

# converts to single daily Rinex
#cmd="teqc $teqcfmt $teqcopt -O.mn \"$code\" -O.mo \"$code\" -O.rt \"$receiver\" -O.at \"$antenna\" -O.ag \"$agency\" -O.op \"$operator\" -O.px ${xyz[$code]} -O.dec $dec $tmpdir/$wildcard > $tmprnx"
echo "teqc $teqcfmt $teqcopt $tmpdir/$wildcard > $tmprnx"
teqc $teqcfmt $teqcopt $tmpdir/$wildcard > $tmprnx


# case A: output directory specified => archiving rinex with proper names (obs and nav)
if [ -d $outdir ]; then
	starttime=$(teqc +meta $tmprnx | grep "start date" | sed -e 's/.*: //' | sed -e 's/[ \t]*//')
	yy=${starttime:2:2}
	echo "   cp -f $tmprnx ${rinex}.${yy}o"
	cp -f $tmprnx ${rinex}.${yy}o
	if [ ! -z "$navfiles" ]; then
		teqc ${teqcfmt}n $teqcopt $navfiles > $tmpnav
		echo "   cp -f $tmpnav ${rinex}.${yy}n"
		cp -f $tmpnav ${rinex}.${yy}n
	fi
# case B: output file specified => write the rinex using given filename
else
	echo "   cp -f $tmprnx $outdir"
	cp -f $tmprnx $outdir
fi

rm -rf $tmpdir

