#!/bin/bash
#
# This script loads configuration defined in WEBOBS.rc file into the current
# environment as variables prefixed by 'WO__'.
#
# It must be 'source'd in your bash script or session:
#  . /etc/webobs.d/../CODE/shells/readconf
#

. /etc/webobs.d/../CODE/shells/wolib.bash
woconf
