#!/bin/bash
# script for execution of deployed Linux 32-bit Matlab applications
#
# Usage:
# 	run_mcc <superproc> args
#
# Sets up the MCR environment for the current $ARCH and executes 
# the specified command.
#

#exe_dir=`dirname "$0"`

# loads all webobs variables as $WO__*
. /etc/webobs.d/../CODE/shells/readconf

if [ "x$1" = "x" ]; then
	echo Usage:
	echo    $0 \<superproc\> args
else
	echo "------------------------------------------------------------------------------"
	echo "--- WEBOBS-${WO__WEBOBS_ID} [${WO__VERSION}] deployed Matlab applications"
	echo
	LD_LIBRARY_PATH=.:${WO__PATH_MCR}/runtime/glnx86 ;
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${WO__PATH_MCR}/bin/glnx86 ;
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${WO__PATH_MCR}/sys/os/glnx86;
	MCRJRE=${WO__PATH_MCR}/sys/java/jre/glnx86/jre/lib/i386 ;
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/native_threads ; 
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/server ;
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/client ;
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE} ;  
	XAPPLRESDIR=${WO__PATH_MCR}/X11/app-defaults ;
	export LD_LIBRARY_PATH;
	export XAPPLRESDIR;
	echo LD_LIBRARY_PATH is ${LD_LIBRARY_PATH};
	superproc="$1"
	shift 1
	args=
	while [ $# -gt 0 ]; do
		token=`echo "$1" | sed 's/ /\\\\ /g'`   # Add blackslash before each blank
		args="${args} ${token}" 
		shift
	done
	echo
	echo SUPERPROC is \""${WO__JOB_MCNODISPLAY}"/$superproc $args\" ;
	eval "${WO__JOB_MCNODISPLAY}"/$superproc $args
fi
exit

