#!/bin/bash
# stationinfo2json
# uses gawk and date
#
# Author: F. Beauducel <beauducel@ipgp.fr>
# Created: 2021-03-08 in Yogyakarta
# Updated: 2021-03-15

# Helper
if [ $# -lt 2 ]; then
	echo "      Syntax: stationinfo2json FILE SITE [DATE]"
	echo " Description: reads station.info file and returns data as JSON"
	echo "   Arguments: FILE = filename of station.info"
	echo "              SITE = site code"
	echo "              DATE = date as YYYY-DDD [HH:MM:SS] (default is current time)"
	echo ""
	exit 0;
fi

if [ -z "$3" ]; then
	DATE=$(date -u +"%Y-%j %H:%M:%S") # current date and time, UT
else
	DATE="$3"
fi

JSON=$(gawk -v site="$2" -v date="$DATE" '
	function trim(s) { gsub(/^[ ]+/, "", s); gsub(/[ ]+$/, "", s); return s }
	BEGIN { FIELDWIDTHS = "6 18 5 4 3 3 4 5 4 3 3 4 9 7 9 9 21 22 7 22 24 21" }
	{
		start = sprintf("%4d-%03d %02d:%02d:%02d",$3, $4, $5, $6, $7);
		stop = sprintf("%4d-%03d %02d:%02d:%02d",$8, $9, $10, $11, $12);
		if (trim($1) == site && date >= start && date <= stop)
			print "{\"site\":\"" site \
				"\",\"name\":\"" trim($2)\
				"\",\"start\":\"" start\
				"\",\"stop\":\"" stop\
				"\",\"antHt\":\"" trim($13)\
				"\",\"HtCod\":\"" trim($14)\
				"\",\"antN\":\"" trim($15)\
				"\",\"antE\":\"" trim($16)\
				"\",\"recType\":\"" trim($17)\
				"\",\"recVers\":\"" trim($18)\
				"\",\"SwVer\":\"" trim($19)\
				"\",\"recSN\":\"" trim($20)\
				"\",\"antType\":\"" trim($21)\
				"\",\"antSN\":\"" trim($22) "\"}"
	}' $1)

echo $JSON
