# Fields definition within Calibration files
# - NbCar   = number of characters for "input" field while editing
# - Default = default value when creating new lines
#   ("auto" means that value will be automatically supplied, eg:
#     Date = today's date, Lat/Lon/Alt = node (station) position, ...)
# - Name    = field display title
# - MSGID   = popup help text (points to i18n translator)
#
# ATTENTION: Fields ordering of DATE, TIME and CHANNEL_NUMBER MUST NOT be changed.
#

# header line that defines hash keys for each parameter type
=key|NbCar|Default|Name|MSGID
DATE|1|auto|Date|help_clb_date
TIME|1|00:00|Time|help_clb_hour
CHANNEL_NUMBER|2|auto|Ch.<br>Nb|help_clb_chnb
CHANNEL_NAME|10||Ch.<br>Name|help_clb_chname
UNIT|5|-|Unit|help_clb_unit
SERIAL_NUMBER|20||S/N|help_clb_sn
CHANNEL_CODE|4||Ch.<br>Code|help_clb_chcode
OFFSET|10|0|Offset|help_clb_offset
CALIBRATION|15|1|Calib|help_clb_factor
GAIN|5|1|Gain|help_clb_gain
MIN_VALUE|6||Min.<br>Value|help_clb_minvalue
MAX_VALUE|6||Max.<br>Value|help_clb_maxvalue
AZIMUTH|3|0|Azim.<br>(°N)|help_clb_azimuth
LATITUDE|8|auto|Latitude<br>(°)|help_clb_latitude
LONGITUDE|9|auto|Longitude<br>(°)|help_clb_longitude
ELEVATION|4|auto|Elevation<br>(m)|help_clb_elevation
DEPTH|2|0|Depth<br>(m)|help_clb_depth
SAMPLING_FREQUENCY|4||S.F.<br>(Hz)|help_clb_sf
DYNAMIC_RANGE|2||Dyn.<br>(bit)|help_clb_dyn
LOCATION_CODE|2||LC|help_clb_lc
THEIA_CATEGORY|32||Theia Cat|help_clb_theia
