#!/bin/bash
P=`dirname $0`
. ${P}/dutils.sh

# can be run any time after linux dependencies installation
# current directory (pwd) MUST be the target webob's CONF/ directory

echo "Creating jobs tables ..."
sqlite3 WEBOBSJOBS.db <<EOF
BEGIN TRANSACTION;
drop table if exists jobs;
create table jobs (
	JID            integer NOT NULL primary key autoincrement,
	VALIDITY       text not null default 'Y',
	RES            text not null default '',
	XEQ1           text not null default '',
	XEQ2           text not null default '',
	XEQ3           text not null default '',
	RUNINTERVAL    integer NOT NULL,
	MAXINSTANCES   integer NOT NULL default 0,
	MAXSYSLOAD     real NOT NULL default 0.7,
	LOGPATH        text,
	LASTSTRTS      integer not null default 0
	);
drop table if exists runs;
create table runs (
	JID            integer NOT NULL,
	KID            integer,
	ORG            text,
	STARTTS        integer NOT NULL default 0,
	ENDTS          integer NOT NULL default 0,
	CMD            text,
	STDPATH        text,
	RC             integer,
	RCMSG          text
	);
COMMIT;
insert into jobs values(null,'N','','\$WEBOBS{JOB_MLNODISPLAY} ','-r "locastat;exit(0)"','',86400,0,0.7,'locastat',0);
insert into jobs values(null,'N','','\$WEBOBS{JOB_MLNODISPLAY} ','-r "gridmaps;exit(0)"','',86400,0,0.7,'gridmaps',0);
insert into jobs values(null,'N','','\$WEBOBS{JOB_MLXVFB} ','-r "sefran3;exit(0)"','',600,0,0.7,'sefran3',0);
insert into jobs values(null,'N','','\$WEBOBS{JOB_MLNODISPLAY} ','-r "gamit(''CGPSWI'');exit(0)"','',86400,0,0.7,'gamit',0);
EOF

echo "Done."
exit 0

