function D = readfmtdata_meteofrance(WO,P,N,F)
%READFMTDATA_METEOFRANCE subfunction of readfmtdata.m
%	
%	From proc P, node N and options F returns data D.
%	See READFMTDATA function for details.
%
%	type: Météo France rain gauges text format
%	P.RAWDATA: full path and filename(s) using bash wildcard facilities (may includes $FID variable) 
%	data format: POSTE;DATE;RR;QRR;TN;QTN;TX;QTX
%
%	output fields:
%		D.t (datenum)
%		D.d (data1 data2 ...)
%
%	Authors: Alexis Bosson, François Beauducel, WEBOBS/IPGP
%	Created: 2016-08-05, in Guadeloupe
%	Updated: 2023-08-30

wofun = sprintf('WEBOBS{%s}',mfilename);

% makes a single file containing rectangular table of numbers, from the raw data

% Temporary file generated by a shell script and then read by matlab
fdat = sprintf('%s/%s.dat',F.ptmp,N.ID);
% Ensure there is no previous file
wosystem(sprintf('rm -f %s',fdat),P);

for a = 1:length(F.raw)
	% Shell command : F.raw contains a wildcard to read all the data files, we just select the raingauge data and convert commas to points
	wosystem(sprintf('awk -F '';'' ''/^%s/ {print $2,gensub(",",".","",$3)+0}'' %s >> %s',N.FID,F.raw{a},fdat),P);
end

% Empty data set if no data read
t = [];
d = [];
% We should have a data file generated by the script
if exist(fdat,'file') 
	% Load a data matrix from the generated file
	dd = load(fdat);
	% If there are data
	if ~isempty(dd)
		% Convert dates 20160125 -> datenum(2016,1,25)
		t = datenum(floor(dd(:,1)/1e4),rem(floor(dd(:,1)/100),100),rem(dd(:,1),100));
		% Data : second column
		d = dd(:,2:end);

		% Remove duplicates
		[t,k] = unique(t);
		% Sort data by date
		[t,kk] = sort(t);
		% ?
		d = dd(k(kk),2:end);
		% Print number of data samples
		fprintf('done (%d samples).\n',length(t));
	end
end
% Warn if no data
if isempty(t)
	fprintf('** WARNING ** no data found!\n');
end

% Set time zone of data
D.t = t - N.UTC_DATA;
% Copy data for resulting matrix
D.d = d;
D.e = [];
% Calibrate the data if calibration files are present
[D.d,D.CLB] = calib(D.t,D.d,N.CLB,'channelcodeorder');
% Set time zone of data again ?
D.t = D.t + P.TZ/24;
