function r=siprefix(u1,u2)
%SIPREFIX International System Unit prefix factor
%	SIPREFIX(U) returns the prefix factor of unit U (string or cell array of strings).
%
%	SIPREFIX(U1,U2) returns the relative ratio of unit U1 to unit U2 (string)
%	
%	The unit must be in the form [prefix]unit. A single letter will be interpreted as
%	base unit and return a factor 1. The prefix µ (micro) can be written as u to avoid
%	any character encoding issue.
%
%	Examples:
%	   siprefix('m') returns 1
%	   siprefix('Tbyte') returns 1e12
%	   siprefix('kg','µg') return 1e9
%
%	Author: F. Beauducel / WEBOBS
%	Created: 2017-01-24 in Yogyakarta, Indonesia

P = { ...
     'y' ,'yocto',1e-24; ...
     'z' ,'zepto',1e-21; ...
     'a' ,'atto' ,1e-18; ...
     'f' ,'femto',1e-15; ...
     'p' ,'pico' ,1e-12; ...
     'n' ,'nano' ,1e-9; ...
     'u' ,'micro',1e-6; ...
     'µ' ,'micro',1e-6; ...
     'm' ,'milli',1e-3; ...
     'c' ,'centi',1e-2; ...
     'd' ,'deci' ,1e-1; ...
     ''  ,''     ,1; ...
     'da','deca' ,1e1; ...
     'h' ,'hecto',1e2; ...
     'k' ,'kilo' ,1e3; ...
     'M' ,'mega' ,1e6; ...
     'G' ,'giga' ,1e9; ...
     'T' ,'tera' ,1e12; ...
     'P' ,'peta' ,1e15; ...
     'E' ,'exa'  ,1e18; ...
     'Z' ,'zetta',1e21; ...
     'Y' ,'yotta',1e24; ...
};

if nargin == 0
	r = P;
	return
end

if ischar(u1)
	u1 = {u1};
end

r = ones(size(u1));

for n = 1:numel(u1)
	if length(u1{n}) > 1
		r(n) = pfactor(u1{n},P);
	end
end

if nargin > 1 && ischar(u2) && length(u2) > 1
	r = r/pfactor(u2,P);
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function f=pfactor(u,P)

k = find(strcmp(P(:,1),u(1)) | strcmp(P(:,1),u(1:(1+(length(u)>1)))));
if ~isempty(k)
	f = P{k,3};
else
	f = 1;
end
