#!/bin/bash
# compress existing SEFRAN3 files
#
# Author: F. Beauducel
# Created: 2020-11-20 in Yogyakarta, Indonesia
# Updated: 2020-11-21

CONFDIR=/etc/webobs.d/
if [ ! -d "$CONFDIR" ]; then
   echo "no active webobs detected. Aborting."
   exit 0
fi
if [ -z $(which convert) ]; then
   echo "you must install pngquant first. Aborting."
   exit 0
fi

NCOLORS=16
PROPELLER=('|' '/' '-' '\')
TMP=/tmp/sefranpngquant.png
SEFRAN_ROOT=$(grep -E "^SEFRAN_ROOT\|" ${CONFDIR}WEBOBS.rc | sed -e 's/.*|//')
C=$(find $CONFDIR -maxdepth 1 -name 'SEFRAN3*.conf')
echo "Found $(echo $C | wc -l) sefran3 in your archives. The compressing process will modify your orginal files. It is strongly recommended to make a backup first."
read -r -p "Confirm compressing process (it will take hours) or make a dry run [y/d/N]? " reply
case $reply in
	[yY])
		dry=$false;;
   [dD])
      dry=$true;;
	*)
		echo "Abort."
      exit 64;;
esac

for s in $C; do
	if [[ ! -z $(grep -E "^ROOT\|" $s) ]]; then
      ROOT=$(grep -E "^ROOT\|" $s | sed -e 's/.*|//' -e "s|\$WEBOBS{SEFRAN_ROOT}|${SEFRAN_ROOT}|")
      NAME=$(grep -E "^TITRE\|" $s | sed -e 's/.*|//')
      NFILE=$(find $ROOT -type f -name "*.png" | wc -l)
      SIZE=$(du -sh $ROOT | sed -E 's/\s+/ /g')
	   echo "---> Compressing sefran3 '$NAME': $NFILE files, $SIZE."
      cd $ROOT
      for y in $(ls -d ????); do
         echo -n "   Year $y 000%  "
         NFILE=$(find $y -type f -name "*.png" | wc -l)
         i=0
         n=1
         for d in $(ls -d $y/*); do
            for f in $(find $d -name "*.png"); do
               if [ ! $dry ]; then
                  tag=$(identify -format %[sefran3*] $f|sed -e 's/sefran3/ -set sefran3/g;s/=/ /g'|tr -d '\n')
                  cat $f | pngquant $NCOLORS | convert - $tag $TMP && mv -f $TMP $f
               fi
               p=$(printf "%03.0f" $(($n*100/$NFILE)))
               echo -ne "\b\b\b\b\b\b$p% ${PROPELLER[$i]}"
               i=$((($i+1)%4))
               n=$(($n+1))
            done
         done
         echo -e "\b\b done ($NFILE files)."
      done
      echo "   New size = $(du -sh $ROOT)"
	fi
done
